### ISSUE TITLE
After uploading the image file, the page become white and show nothing

### ISSUE THREAD

**Issue by CommanderXL** [rosshinkley/nightmare-upload#3]
Well. In my test, I use nightmare-upload plugin. But after uploading the image file successfully, the page become white and show nothing? - -

**Comment by CommanderXL** [comment]
Well. I know how to solve this problem. I had write relative path of image file. So it has the problem as I said. Now I change the image file to absolute path. It works!

**Comment by rosshinkley** [comment]
Hm, relative paths should still work.  I'll open an issue to look in to that.  Thanks for bringing it to my attention!
